---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex-operator-dexsso
rules:
- apiGroups: ["dex.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"] # To manage its own resources, dex must be able to create customresourcedefinitions
- apiGroups: [""]
  resources: ["configmaps"] # dex pods needs
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"] # dex pods needs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-operator-dexsso
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex-operator-dexsso
subjects:
- kind: ServiceAccount
  name: dex-operator-dexsso
  namespace: dex-gitops
