# permissions for end users to edit dexconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dexconfig-editor-role
rules:
- apiGroups:
  - identitatem.io
  resources:
  - dexconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identitatem.io
  resources:
  - dexconfigs/status
  verbs:
  - get
