# permissions for end users to view dexconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dexconfig-viewer-role
rules:
- apiGroups:
  - identitatem.io
  resources:
  - dexconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identitatem.io
  resources:
  - dexconfigs/status
  verbs:
  - get
